# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start-page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(715, 568))
        MainWindow.setMaximumSize(QtCore.QSize(715, 568))
        MainWindow.setStyleSheet("*{\n"
"font-family: \'Comfortaa\', cursive;\n"
"font-weight: bold;\n"
"color: #464646;\n"
"}\n"
"QMainWindow{\n"
"background: white;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"width: 10px;\n"
"  border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"border: 2px dashed #464646;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(101, 199, 198);\n"
"}\n"
"QPushButton:pressed {\n"
"   background: rgb(240, 249, 248);\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainText = QtWidgets.QLabel(self.centralwidget)
        self.mainText.setStyleSheet("font-size: 30px;\n"
"font-weight: bold;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.mainText.setObjectName("mainText")
        self.gridLayout.addWidget(self.mainText, 1, 2, 1, 1)
        self.add_new_member_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_new_member_btn.setStyleSheet("*{\n"
"border: 2px dashed  rgb(101, 199, 198);\n"
"color: rgb(101, 199, 198);\n"
"padding: 20px;\n"
"margin-left: 8px;\n"
"margin-right: 8px;\n"
"border-radius: 10px;\n"
"margin-bottom: 10px;\n"
"font-size: 40px;\n"
"}\n"
"*:hover{\n"
"border: 2px solid  rgb(101, 199, 198);\n"
"background: whitesmoke;\n"
"}")
        self.add_new_member_btn.setObjectName("add_new_member_btn")
        self.gridLayout.addWidget(self.add_new_member_btn, 3, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("padding: 0px;")
        self.label.setFrameShape(QtWidgets.QFrame.HLine)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("border: 0px;\n"
"padding: 0px;\n"
"background: transparent;")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 580, 324))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(574, 0))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 6, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setStyleSheet("border-image: url(img/ad-6.png);\n"
"margin: 5px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.leftTab = QtWidgets.QFrame(self.centralwidget)
        self.leftTab.setMaximumSize(QtCore.QSize(135, 16777215))
        self.leftTab.setStyleSheet("*{\n"
"background-color: rgb(240, 249, 248);\n"
"}\n"
"QPushButton{\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"border: 0px solid none;\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"border: 2px dashed rgb(101, 199, 198);\n"
"}\n"
"#leftTab{\n"
"padding-left: 0px;\n"
"padding-right: 0px;\n"
"}")
        self.leftTab.setObjectName("leftTab")
        self.leftTabGrid = QtWidgets.QGridLayout(self.leftTab)
        self.leftTabGrid.setContentsMargins(0, 0, 0, 6)
        self.leftTabGrid.setObjectName("leftTabGrid")
        self.logoPhoto = QtWidgets.QLabel(self.leftTab)
        self.logoPhoto.setStyleSheet("padding: 30px;\n"
"margin: 30px;\n"
"border-image: url(img/clear-logo.png);\n"
"")
        self.logoPhoto.setText("")
        self.logoPhoto.setObjectName("logoPhoto")
        self.leftTabGrid.addWidget(self.logoPhoto, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftTabGrid.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.leftTab, 0, 0, 8, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setStyleSheet("border: 2px solid  rgb(101, 199, 198);\n"
"border-radius: 10px;\n"
"margin-left: 5px;\n"
"margin-right: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainText.setText(_translate("MainWindow", "Реєстратура"))
        self.add_new_member_btn.setText(_translate("MainWindow", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
